"""Assemble the FastMCP server from the bundled OpenAPI spec.

Every Freebox operation becomes an MCP tool (generated by FastMCP from the spec).
A handful of hand-written lifecycle tools cover what the spec cannot express:
the app-authorization handshake and session/status introspection.
"""

from __future__ import annotations

import asyncio
import logging

import httpx
from fastmcp import FastMCP
from fastmcp.server.providers.openapi import MCPType, RouteMap

from .auth import (
    BoxCredentials,
    TokenStore,
    request_authorization,
    wait_for_authorization,
)
from .client import SessionManager, build_client, build_session_manager
from .config import Settings, load_settings
from .discovery import Discovery, Endpoint, choose_endpoint
from .spec import load_spec

log = logging.getLogger("freebox_mcp.server")

_DEFAULT_DISCOVERY = Discovery(
    api_domain=None,
    https_port=None,
    https_available=False,
    api_base_url="/api/",
    api_version="8.0",
    box_model_name=None,
    uid=None,
)


def _resolve_endpoint(settings: Settings) -> Endpoint:
    try:
        return choose_endpoint(settings)
    except Exception as exc:  # noqa: BLE001
        log.warning("Freebox discovery failed (%r); defaulting to LAN HTTP.", exc)
        return Endpoint(
            base_url="http://mafreebox.freebox.fr",
            secure=False,
            api_path_prefix=_DEFAULT_DISCOVERY.api_path_prefix,
            discovery=_DEFAULT_DISCOVERY,
        )


def _add_lifecycle_tools(
    mcp: FastMCP,
    settings: Settings,
    endpoint: Endpoint,
    store: TokenStore,
    session: SessionManager,
) -> None:
    disc = endpoint.discovery

    @mcp.tool(tags={"freebox-auth"})
    async def freebox_status() -> dict:
        """Report discovery, transport, and authorization status of the Freebox connection."""
        return {
            "box_model": disc.box_model_name,
            "api_version": disc.api_version,
            "uid": disc.uid,
            "transport": "https" if endpoint.secure else "http",
            "secure": endpoint.secure,
            "base_url": endpoint.base_url,
            "api_path_prefix": endpoint.api_path_prefix,
            "registered": session.registered,
            "permissions": session.permissions,
        }

    @mcp.tool(tags={"freebox-auth"})
    async def freebox_login() -> dict:
        """Open (or refresh) a Freebox session and return the granted permissions."""
        await session.refresh()
        return {"logged_in": True, "permissions": session.permissions}

    @mcp.tool(tags={"freebox-auth"})
    async def freebox_authorize(timeout_seconds: int = 90) -> dict:
        """Register this app with the Freebox. The user must press the button on the
        Freebox front panel within `timeout_seconds` to grant access."""

        def _register() -> tuple[str, int, str]:
            from .tls import freebox_ssl_context

            verify = freebox_ssl_context(str(settings.cert_bundle)) if endpoint.secure else True
            with httpx.Client(
                base_url=endpoint.base_url, verify=verify, timeout=settings.request_timeout
            ) as http:
                req = request_authorization(
                    http,
                    endpoint.api_path_prefix,
                    settings.app_id,
                    settings.app_name,
                    settings.app_version,
                    settings.device_name,
                )
                status = wait_for_authorization(
                    http, endpoint.api_path_prefix, req.track_id, timeout=timeout_seconds
                )
                return req.app_token, req.track_id, status

        app_token, track_id, status = await asyncio.to_thread(_register)
        if status == "granted":
            store.set(
                disc.uid,
                BoxCredentials(
                    app_id=settings.app_id,
                    app_token=app_token,
                    track_id=track_id,
                    box_model=disc.box_model_name,
                ),
            )
            session.set_app_token(app_token, settings.app_id)
            return {"status": "granted", "message": "Authorized; credentials saved."}
        return {
            "status": status,
            "message": "Not granted. Press the button on the Freebox front panel and retry.",
        }


def _route_maps(settings: Settings) -> list[RouteMap]:
    # Authentication routes are always replaced by the lifecycle tools.
    maps = [RouteMap(pattern=r"^/login/", mcp_type=MCPType.EXCLUDE)]
    if settings.include_sections:
        # Allow-list: expose only the requested sections, drop everything else.
        for section in settings.include_sections:
            maps.append(RouteMap(tags={section}, mcp_type=MCPType.TOOL))
        maps.append(RouteMap(mcp_type=MCPType.EXCLUDE))
    else:
        # Deny-list (possibly empty): hide the excluded sections, keep the rest.
        for section in settings.exclude_sections:
            maps.append(RouteMap(tags={section}, mcp_type=MCPType.EXCLUDE))
        maps.append(RouteMap(mcp_type=MCPType.TOOL))
    return maps


def create_server(settings: Settings | None = None) -> FastMCP:
    settings = settings or load_settings()
    spec = load_spec()
    store = TokenStore(settings.credentials_path)
    endpoint = _resolve_endpoint(settings)
    session = build_session_manager(settings, endpoint, store)
    client = build_client(settings, endpoint, session)

    mcp = FastMCP.from_openapi(
        spec,
        client=client,
        name="Freebox OS",
        route_maps=_route_maps(settings),
        validate_output=False,
    )
    _add_lifecycle_tools(mcp, settings, endpoint, store, session)
    return mcp
